[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
hola_mundo = "Eg9n2jQm57XDTyhESDzbXp96CunY5SFirmNovq49UBxr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "./world-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
