[toolchain]

[features]
resolution = true
skip-lint = false

[programs.mainnet]
hola_mundo = "EkrwchyoN347S3jgCTnVjVnMayqXyFgsZQzdSJDcVbuZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.mainnet-beta.solana.com"
wallet = "/home/jong/.config/solana/hola-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
